# Generated by Django 2.1.7 on 2019-03-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20190312_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
