# Generated by Django 2.1.7 on 2019-03-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20190313_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='technology_type',
        ),
        migrations.AddField(
            model_name='technology_type',
            name='technology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.Technology'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technology',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/technology/'),
        ),
    ]
