# Generated by Django 2.1.7 on 2019-03-13 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20190313_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='technology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.Technology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='technology_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hr.Technology_type'),
            preserve_default=False,
        ),
    ]
