# Generated by Django 2.1.7 on 2019-03-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_auto_20190313_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology_type',
            options={'ordering': ('name',)},
        ),
    ]
