# Generated by Django 2.1.5 on 2019-03-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_auto_20190314_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('PHP', 'PHP'), ('Python', 'Python'), ('JavaScript', 'JavaScript'), ('C#', 'C#'), ('Java', 'Java'), ('C', 'C'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('SQL', 'SQL'), ('TypeScript', 'TypeScript'), ('Ruby', 'Ruby')], max_length=100, unique=True),
        ),
    ]
