# Generated by Django 2.1.5 on 2019-03-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_auto_20190314_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_tech',
            name='technology',
        ),
        migrations.AddField(
            model_name='employee_tech',
            name='technology',
            field=models.ManyToManyField(to='hr.Technology'),
        ),
        migrations.RemoveField(
            model_name='employee_tech',
            name='technology_type',
        ),
        migrations.AddField(
            model_name='employee_tech',
            name='technology_type',
            field=models.ManyToManyField(to='hr.Technology_type'),
        ),
    ]
