# Generated by Django 2.1.5 on 2019-03-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_auto_20190314_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee_tech',
            name='other',
            field=models.ManyToManyField(to='hr.Other'),
        ),
    ]
