# Generated by Django 2.1.5 on 2019-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_auto_20190314_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='technology_type',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
