# Generated by Django 2.1.5 on 2019-03-15 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_auto_20190315_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology_type',
            name='technology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.Technology'),
            preserve_default=False,
        ),
    ]
